services:
    grabber_proxy_config_manager:
        class: Grabber\Bundle\GrabBundle\Service\ProxyConfigManager
        arguments: [%proxy_file_config_path%]

    grabber_proxy_client:
        class: GuzzleHttp\Client
        arguments: [{base_uri: %url_proxy_site%}]

    grabber_proxy_grabber:
        class: Grabber\Bundle\GrabBundle\Grabber\ProxyGrabber
        arguments: [@grabber_proxy_config_manager, @grabber_proxy_client]

    grabber_locality_manager:
        class: Grabber\Bundle\GrabBundle\Service\LocalityManager
        arguments: [@google_api_manager, @doctrine.orm.entity_manager]

    grabber_category_manager:
        class: Grabber\Bundle\GrabBundle\Service\CategoryManager
        arguments: [@doctrine.orm.entity_manager]

    grabber_besplatka_service:
        class: Grabber\Bundle\GrabBundle\Grabber\BesplatkaGrabber
        arguments: [@grabber_locality_manager, @grabber_category_manager, @grabber_proxy_client]


#    grabber_grab.example:
#        class: Grabber\Bundle\GrabBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
#        class: GuzzleHttp\Client
#        arguments: [{base_uri: %sms_chat_api_url%}]
