services:
    grabber_proxy_config_manager:
        class: Grabber\Bundle\GrabBundle\Service\ProxyConfigManager
        arguments: [%proxy_file_config_path%]

    grabber_proxy_client:
        class: GuzzleHttp\Client
        arguments: [{base_uri: %url_proxy_site%}]

    grabber_proxy_grabber:
        class: Grabber\Bundle\GrabBundle\Grabber\ProxyGrabber
        arguments: [@grabber_proxy_config_manager, @grabber_proxy_client]

    grabber_client_manager:
        class: Grabber\Bundle\GrabBundle\Client\ClientManager
        arguments: [@grabber_proxy_config_manager]

    grabber_locality_manager:
        class: Grabber\Bundle\GrabBundle\Service\LocalityManager
        arguments: [@google_api_manager, @doctrine.orm.entity_manager]

    grabber_category_manager:
        class: Grabber\Bundle\GrabBundle\Service\CategoryManager
        arguments: [@doctrine.orm.entity_manager]

    grabber_person_manager:
        class: Grabber\Bundle\GrabBundle\Service\PersonManager
        arguments: [@doctrine.orm.entity_manager]

    grabber_announce_manager:
        class: Grabber\Bundle\GrabBundle\Service\AnnounceManager
        arguments: [@doctrine.orm.entity_manager]

    grabber_besplatka_service:
        class: Grabber\Bundle\GrabBundle\Grabber\BesplatkaGrabber
        arguments: [@grabber_locality_manager, @grabber_category_manager, @grabber_proxy_client]

    grabber_parce_command_factory:
        class: Grabber\Bundle\GrabBundle\Factory\ParseCommandFactory

    ##################   HANDLERS   ##################

    grabber_announce_handler:
        class: Grabber\Bundle\GrabBundle\Handler\AnnounceHandler
        arguments: [@grabber_client_manager, @grabber_parce_command_factory]
        calls:
            - [setPersonManager,   [@grabber_person_manager]  ]
            - [setLocalityManager, [@grabber_locality_manager]]
            - [setAnnounceManager, [@grabber_announce_manager]]

    grabber_announce_list_handler:
        class: Grabber\Bundle\GrabBundle\Handler\AnnounceListHandler
        arguments: [@grabber_client_manager, @grabber_parce_command_factory]
        calls:
            - [setHandler, [@grabber_announce_handler]]

    grabber_page_handler:
        class: Grabber\Bundle\GrabBundle\Handler\PageHandler
        arguments: [@grabber_client_manager, @grabber_parce_command_factory]
        calls:
            - [setHandler, [@grabber_announce_list_handler]]

    grabber_category_handler:
        class: Grabber\Bundle\GrabBundle\Handler\CategoryHandler
        arguments: [@grabber_client_manager, @grabber_parce_command_factory]
        calls:
            - [setCategoryManager, [@grabber_category_manager]]
            - [setHandler, [@grabber_page_handler]]

    grabber_region_handler:
        class: Grabber\Bundle\GrabBundle\Handler\RegionHandler
        arguments: [@grabber_client_manager, @grabber_parce_command_factory]
        calls:
            - [setLocalityManager, [@grabber_locality_manager]]
            - [setHandler, [@grabber_category_handler]]

    grabber_simple_grabber:
        class: Grabber\Bundle\GrabBundle\Grabber\SimpleGrabber
        calls:
            - [setHandle, [@grabber_region_handler]]

#    grabber_grab.example:
#        class: Grabber\Bundle\GrabBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
#        class: GuzzleHttp\Client
#        arguments: [{base_uri: %sms_chat_api_url%}]
