services:

    google_api_client:
        class: GuzzleHttp\Client

    google_api_factory:
        class: Grabber\Bundle\GoogleApiBundle\Factory\Factory
        arguments: [@google_api_client, %google_geocode_uri%]

    google_api_manager:
        class: Grabber\Bundle\GoogleApiBundle\Service\GeoCodeManager
        arguments: [@google_api_factory]

#    grabber_google_api.example:
#        class: Grabber\Bundle\GoogleApiBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
